name: Iris RESTful Server Linux Docker CI

on:
  workflow_call:
    inputs:
        os: 
            required: true
            type: string
        build_type:
            required: true
            type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ${{ github.workspace }}/Docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/iris-restful:latest # Tag the image with the repository name and 'latest'