name: Iris RESTful Server Linux Docker CI

on:
  workflow_call:
    inputs:
        os: 
            required: true
            type: string
        build_type:
            required: true
            type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    # permissions:
    #   contents: read
    #   packages: write # Grant write permissions for packages (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Build
        run: >
            docker build -f ${{ github.workspace }}/Docker/Dockerfile ${{ github.workspace }}
        
        # with:
        #     platforms: linux/arm64, linux/amd64
            # "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/386"

    #   - name: Login to GHCR
    #     uses: docker/login-action@v3
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@v5
    #     with:
    #       file: ${{ github.workspace }}/Docker/Dockerfile
    #       push: false
    #       tags: ghcr.io/${{ github.repository }}:latest # Tag the image with the repository name and 'latest'