name: Iris RESTful Server Linux Docker CI

on:
  release:
    types: [published]


jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        build_type: [Release]
      
        include:
          - os: ubuntu-latest
            name: ubuntu
            arch: aarch64
          - os: ubuntu-24.04-arm
            name: ubuntu
            arch: amd64
    uses: ./.github/workflows/build-docker-linux.yml
    with: 
      os: ${{ matrix.os }}
      push: true