name: Iris RESTful Server Linux Docker CI

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Grant write permissions for packages (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # with:
        #     platforms: linux/arm64, linux/amd64
            # "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/386"

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ${{ github.workspace }}/Docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/iris-restful:latest # Tag the image with the repository name and 'latest'