name: Iris RESTful Linux Docker CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*/README.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '*/README.md'

jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        build_type: [Release]
      
        include:
          - os: ubuntu-latest
            name: ubuntu
            arch: aarch64
          - os: ubuntu-24.04-arm
            name: ubuntu
            arch: amd64
    uses: ./.github/workflows/build-docker-linux.yml
    with: 
      os: ${{ matrix.os }}
      build_type: ${{ matrix.build_type }}
      

