name: Iris RESTful Linux Docker CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*/README.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '*/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner name as environment variable
        id: strings
        shell: bash
        run: |
          INPUT=${{ github.repository_owner }}; echo "OWNER=${INPUT,,}">>${GITHUB_OUTPUT}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ${{ github.workspace }}/Docker/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.strings.outputs.OWNER }}/iris-restful:latest 
          platforms: "linux/arm64,linux/arm/v7,linux/arm/v6,linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386"

